/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Requerimiento_3;
import static vista.VistaRequerimientos.controlador;

/**
 *
 * @author sebas
 */
public class consulta_3 extends javax.swing.JPanel {

    /**
     * Creates new form consulta_3
     */
    public consulta_3() throws SQLException {
        initComponents();
        actualizarTabla();
    }

    public void actualizarTabla() throws SQLException{
    
        ArrayList<modelo.Requerimiento_3> requerimiento3 = controlador.consultarRequerimiento3();
        
        DefaultTableModel modelo = (DefaultTableModel) TableConsulte3.getModel();
        
        while (modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for(modelo.Requerimiento_3 requ: requerimiento3){
            Object[] fila = new Object [numcols];
        
            fila[0] = requ.getCargo();
            fila[1] = requ.getMaxSalario();
            
            modelo.addRow(fila);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsulte3 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 233, 243));
        setPreferredSize(new java.awt.Dimension(320, 302));
        setLayout(new java.awt.GridLayout(1, 0));

        TableConsulte3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cargo", "MaxSalario"
            }
        ));
        jScrollPane1.setViewportView(TableConsulte3);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableConsulte3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
