/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static vista.VistaRequerimientos.controlador;

/**
 *
 * @author sebas
 */
public class consulta_2 extends javax.swing.JPanel {

    /**
     * Creates new form consulta_2
     */
    public consulta_2() throws SQLException {
        initComponents();
        actualizarTabla();
    }

     public void actualizarTabla() throws SQLException{
        ArrayList<modelo.Requerimiento_2> requerimiento2= controlador.consultarRequerimiento2();
        
        DefaultTableModel modelo = (DefaultTableModel) TableConsulte_2.getModel();
        
        while (modelo.getRowCount() > 0){
         modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for (modelo.Requerimiento_2 reque: requerimiento2){
            Object[] fila = new Object[numcols];
            
            fila[0] = reque.getConstructora();
            fila[1] = reque.getProveedor();
            fila[2] = reque.getPagado();
            
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsulte_2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 233, 243));
        setLayout(new java.awt.GridLayout(1, 0));

        TableConsulte_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Proveedor", "Constructora", "Pagado"
            }
        ));
        TableConsulte_2.setPreferredSize(new java.awt.Dimension(320, 302));
        jScrollPane1.setViewportView(TableConsulte_2);
        if (TableConsulte_2.getColumnModel().getColumnCount() > 0) {
            TableConsulte_2.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableConsulte_2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
