/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.sql.SQLException;
import modelo.Requerimiento_1;
import java.util.ArrayList;
import static vista.VistaRequerimientos.controlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class consulta extends javax.swing.JPanel {

    /**
     * Creates new form consulta
     */
    public consulta() throws SQLException {
        initComponents();
        actualizarTabla();
    }
    
    public void actualizarTabla() throws SQLException{
        ArrayList<modelo.Requerimiento_1> requerimiento1= controlador.consultarRequerimiento1();
        
        DefaultTableModel modelo = (DefaultTableModel) TableConsulte_1.getModel();
        
        while (modelo.getRowCount() > 0){
         modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for (Requerimiento_1 reque: requerimiento1){
            Object[] fila = new Object[numcols];
            
            fila[0] = reque.getConstructora();
            fila[1] = reque.getCiudad();
            fila[2] = reque.getBanco();
            fila[3] = reque.getPorcentaje();
            fila[4] = reque.getClasificacion();
            fila[5] = reque.getFecha();
                    
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableConsulta_1 = new javax.swing.JScrollPane();
        TableConsulte_1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 233, 243));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(345, 327));
        setLayout(new java.awt.GridLayout(1, 0));

        TableConsulta_1.setPreferredSize(new java.awt.Dimension(580, 402));

        TableConsulte_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Constructora", "Ciudad", "Banco", "Porcentaje", "Clasificacion", "Fecha"
            }
        ));
        TableConsulta_1.setViewportView(TableConsulte_1);

        add(TableConsulta_1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TableConsulta_1;
    private javax.swing.JTable TableConsulte_1;
    // End of variables declaration//GEN-END:variables
}
